<?php
/**
 * Stream a simple "Health Card" PDF (Name / Gender / Blood Group / Email / Phone
 * + ABHA details if linked) for a patient linked to the authenticated doctor.
 * GET ?patient_id=..
 */
require_once __DIR__ . '/../auth/guard.php';
require_once dirname(dirname(__DIR__)) . '/config/connect.php';
require_once dirname(dirname(__DIR__)) . '/vendor/autoload.php';

$payload = doctor_jwt_guard(true);
if (!$payload) { http_response_code(401); exit('Unauthorized'); }
$doctor_id = (int)($payload['doctor_id'] ?? $payload['sub'] ?? 0);

$patient_id = (int)($_GET['patient_id'] ?? 0);
if (!$patient_id) { http_response_code(400); exit('patient_id is required'); }

$hasAccess = false;
$chk = $conn->prepare("SELECT 1 FROM doctor_patients WHERE doctor_id=? AND patient_id=? LIMIT 1");
$chk->bind_param('ii', $doctor_id, $patient_id);
$chk->execute();
if ($chk->get_result()->fetch_row()) $hasAccess = true;

if (!$hasAccess) {
    $chk2 = $conn->prepare("SELECT 1 FROM appointments WHERE doctor_id=? AND user_id=? LIMIT 1");
    $chk2->bind_param('ii', $doctor_id, $patient_id);
    $chk2->execute();
    if ($chk2->get_result()->fetch_row()) $hasAccess = true;
}
if (!$hasAccess) { http_response_code(403); exit('You do not have access to this patient'); }

$stmt = $conn->prepare("SELECT * FROM users WHERE id=? LIMIT 1");
$stmt->bind_param('i', $patient_id);
$stmt->execute();
$p = $stmt->get_result()->fetch_assoc();
if (!$p) { http_response_code(404); exit('Patient not found'); }

$fullName = trim(($p['name'] ?? '') . ' ' . ($p['last_name'] ?? '')) ?: 'Unknown Patient';

$pdf = new FPDF('P', 'mm', 'A4');
$pdf->AddPage();
$pdf->SetFont('Helvetica', 'B', 18);
$pdf->SetTextColor(12, 116, 197);
$pdf->Cell(0, 12, 'Health Card', 0, 1, 'C');
$pdf->SetTextColor(0, 0, 0);
$pdf->Ln(4);

$pdf->SetFillColor(12, 116, 197);
$pdf->SetTextColor(255, 255, 255);
$pdf->SetFont('Helvetica', 'B', 12);
$pdf->Cell(0, 9, ' Profile Information', 0, 1, 'L', true);
$pdf->SetTextColor(0, 0, 0);
$pdf->Ln(2);

function pdf_row($pdf, $label, $value) {
    $pdf->SetFont('Helvetica', 'B', 11);
    $pdf->Cell(50, 8, $label, 0, 0);
    $pdf->SetFont('Helvetica', '', 11);
    $pdf->Cell(0, 8, $value !== '' ? $value : '-', 0, 1);
}

pdf_row($pdf, 'Name:', $fullName);
pdf_row($pdf, 'Gender:', $p['gender'] ?? '');
pdf_row($pdf, 'Blood Group:', $p['blood_group'] ?? '');
pdf_row($pdf, 'Email:', $p['email'] ?? '');
pdf_row($pdf, 'Phone No:', $p['mobile'] ?? '');

if (!empty($p['abha_id'])) {
    $pdf->Ln(4);
    $pdf->SetFillColor(2, 201, 184);
    $pdf->SetTextColor(255, 255, 255);
    $pdf->SetFont('Helvetica', 'B', 12);
    $pdf->Cell(0, 9, ' ABHA Details', 0, 1, 'L', true);
    $pdf->SetTextColor(0, 0, 0);
    $pdf->Ln(2);
    pdf_row($pdf, 'ABHA Number:', $p['abha_id']);
    pdf_row($pdf, 'ABHA Address:', $p['abha_address'] ?? '');
    pdf_row($pdf, 'Status:', $p['abha_verified'] ? 'Verified' : 'Unverified');
}

$pdf->Ln(6);
$pdf->SetFont('Helvetica', 'I', 8);
$pdf->SetTextColor(150, 150, 150);
$pdf->Cell(0, 6, 'Generated by REJUVENATE Digital Health on ' . date('d M Y H:i'), 0, 1);

$safeName = preg_replace('/[^A-Za-z0-9_-]/', '_', $fullName);
$pdf->Output('D', "health-card-{$safeName}.pdf");
