-- ============================================================
-- Migration: parent_consent_forms
-- Run once on: rej_digital_health_db (MariaDB 10.4)
--   mysql -u root rej_digital_health_db < database/migration_parent_consent_forms.sql
--
-- School parent-consent submissions (school/parent-consent.php), reviewed in
-- admin/parent-consents.php and consumed by the doctor school-health flow.
--
-- Previously the table AND ~40 column/index additions were run at runtime by
-- school/parent-consent.php and admin/parent-consents.php on every page load.
-- This file is the full current shape (fresh installs) plus every additive
-- ALTER as `IF NOT EXISTS` (existing installs on any prior version).
-- ============================================================

CREATE TABLE IF NOT EXISTS `parent_consent_forms` (
  `id`                    INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `token`                 VARCHAR(64)  NOT NULL,
  `school_id`             INT UNSIGNED DEFAULT NULL,
  `member_id`             INT          DEFAULT NULL,
  `school_name_manual`    VARCHAR(200) DEFAULT NULL,
  `plan_id`               INT UNSIGNED DEFAULT NULL,
  `plan_name`             VARCHAR(120) DEFAULT NULL,
  `plan_price`            DECIMAL(10,2) DEFAULT NULL,
  `payment_status`        ENUM('pending','paid','failed') NOT NULL DEFAULT 'pending',
  `razorpay_order_id`     VARCHAR(64)  DEFAULT NULL,
  `razorpay_payment_id`   VARCHAR(64)  DEFAULT NULL,
  `paid_at`               DATETIME     DEFAULT NULL,
  `parent_name`           VARCHAR(150) NOT NULL,
  `relation`              ENUM('Father','Mother','Guardian','Other') NOT NULL DEFAULT 'Father',
  `parent_mobile`         VARCHAR(15)  NOT NULL,
  `parent_email`          VARCHAR(150) DEFAULT NULL,
  `parent_aadhar_last4`   CHAR(4)      DEFAULT NULL,
  `parent_aadhar_mobile`  VARCHAR(15)  DEFAULT NULL,
  `student_name`          VARCHAR(150) NOT NULL,
  `student_dob`           DATE         DEFAULT NULL,
  `student_gender`        ENUM('Male','Female','Other') DEFAULT NULL,
  `student_class`         VARCHAR(20)  DEFAULT NULL,
  `student_section`       VARCHAR(10)  DEFAULT NULL,
  `student_roll_no`       VARCHAR(30)  DEFAULT NULL,
  `student_apaar_id`      VARCHAR(40)  DEFAULT NULL,
  `student_address`       TEXT         DEFAULT NULL,
  `student_city`          VARCHAR(100) DEFAULT NULL,
  `student_state`         VARCHAR(100) DEFAULT NULL,
  `student_pincode`       VARCHAR(10)  DEFAULT NULL,
  `student_abha_number`   VARCHAR(20)  DEFAULT NULL,
  `student_abha_address`  VARCHAR(100) DEFAULT NULL,
  `student_abha_status`   VARCHAR(20)  DEFAULT NULL,
  `blood_group`           VARCHAR(10)  DEFAULT NULL,
  `height_cm`             DECIMAL(5,1) DEFAULT NULL,
  `weight_kg`             DECIMAL(5,1) DEFAULT NULL,
  `bmi`                   DECIMAL(5,1) DEFAULT NULL,
  `known_allergies`       TEXT         DEFAULT NULL,
  `existing_conditions`   TEXT         DEFAULT NULL,
  `current_medications`   TEXT         DEFAULT NULL,
  `health_data`           LONGTEXT     DEFAULT NULL CHECK (json_valid(`health_data`)),
  `file_id_proof`         VARCHAR(255) DEFAULT NULL,
  `file_eye_report`       VARCHAR(255) DEFAULT NULL,
  `file_dental_report`    VARCHAR(255) DEFAULT NULL,
  `file_vaccination_cert` VARCHAR(255) DEFAULT NULL,
  `file_medical_records`  VARCHAR(255) DEFAULT NULL,
  `consent_items`         LONGTEXT     NOT NULL CHECK (json_valid(`consent_items`)),
  `consent_given`         TINYINT(1)   NOT NULL DEFAULT 0,
  `declaration_text`      TEXT         DEFAULT NULL,
  `ip_address`            VARCHAR(45)  DEFAULT NULL,
  `user_agent`            VARCHAR(255) DEFAULT NULL,
  `submitted_at`          DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `status`                ENUM('pending','reviewed','archived') NOT NULL DEFAULT 'pending',
  `source`                ENUM('parent','doctor') NOT NULL DEFAULT 'parent',
  `recorded_by_doctor_id` INT          DEFAULT NULL,
  `linked_at`             DATETIME     DEFAULT NULL,
  `reviewed_at`           DATETIME     DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `token`           (`token`),
  KEY        `idx_school`      (`school_id`),
  KEY        `idx_mobile`      (`parent_mobile`),
  KEY        `idx_member`      (`member_id`),
  KEY        `idx_pcf_order`   (`razorpay_order_id`),
  KEY        `idx_pcf_payment` (`payment_status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ── Additive columns/indexes for databases created on an older version ──
ALTER TABLE `parent_consent_forms`
  ADD COLUMN IF NOT EXISTS `member_id`             INT          DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `school_name_manual`    VARCHAR(200) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `plan_id`               INT UNSIGNED DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `plan_name`             VARCHAR(120) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `plan_price`            DECIMAL(10,2) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `payment_status`        ENUM('pending','paid','failed') NOT NULL DEFAULT 'pending',
  ADD COLUMN IF NOT EXISTS `razorpay_order_id`     VARCHAR(64)  DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `razorpay_payment_id`   VARCHAR(64)  DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `paid_at`               DATETIME     DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `parent_aadhar_mobile`  VARCHAR(15)  DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `student_apaar_id`      VARCHAR(40)  DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `student_address`       TEXT         DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `student_city`          VARCHAR(100) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `student_state`         VARCHAR(100) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `student_pincode`       VARCHAR(10)  DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `student_abha_number`   VARCHAR(20)  DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `student_abha_address`  VARCHAR(100) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `student_abha_status`   VARCHAR(20)  DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `height_cm`             DECIMAL(5,1) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `weight_kg`             DECIMAL(5,1) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `bmi`                   DECIMAL(5,1) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `health_data`           LONGTEXT     DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `file_id_proof`         VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `file_eye_report`       VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `file_dental_report`    VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `file_vaccination_cert` VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `file_medical_records`  VARCHAR(255) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `source`                ENUM('parent','doctor') NOT NULL DEFAULT 'parent',
  ADD COLUMN IF NOT EXISTS `recorded_by_doctor_id` INT          DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `linked_at`             DATETIME     DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `reviewed_at`           DATETIME     DEFAULT NULL,
  ADD INDEX  IF NOT EXISTS `idx_member`      (`member_id`),
  ADD INDEX  IF NOT EXISTS `idx_pcf_order`   (`razorpay_order_id`),
  ADD INDEX  IF NOT EXISTS `idx_pcf_payment` (`payment_status`);
