<?php

/**
 * AbdmGatewaySignature — Verification of ABDM Consent Artefact & Gateway JWS signatures.
 *
 * In ABDM Milestone 2, consent notifications include a detached JWS signature
 * generated by the Consent Manager (CM):
 *   Header: e.g. {"alg":"RS256","b64":false,"crit":["b64"]}
 *   Payload: detached (the serialized consent JSON string)
 *   Signature: RS256 signature over "<header>.<payload>"
 */
class AbdmGatewaySignature
{
    /**
     * Verify a detached or standard JWS signature from ABDM Gateway / CM.
     *
     * @param string $payload The raw string payload (e.g. consent JSON)
     * @param string $signature The JWS token string (detached "header..signature" or full "header.payload.signature")
     * @param string|null $certPem Optional X.509 Certificate or Public Key in PEM format
     * @return array{verified: bool, error: ?string}
     */
    public static function verify(string $payload, string $signature, ?string $certPem = null): array
    {
        $signature = trim($signature);
        if ($signature === '') {
            return ['verified' => false, 'error' => 'Signature is empty'];
        }

        $parts = explode('.', $signature);
        if (count($parts) !== 3) {
            return ['verified' => false, 'error' => 'Invalid JWS format: expected 3 dot-separated segments'];
        }

        [$headerB64, $payloadB64, $sigB64] = $parts;

        $headerJson = self::base64UrlDecode($headerB64);
        $header = json_decode($headerJson, true);
        if (!is_array($header) || empty($header['alg'])) {
            return ['verified' => false, 'error' => 'Invalid JWS header'];
        }

        if ($header['alg'] !== 'RS256' && $header['alg'] !== 'SHA256withRSA') {
            return ['verified' => false, 'error' => 'Unsupported JWS algorithm: ' . $header['alg']];
        }

        $contentToVerify = $headerB64 . '.' . ($payloadB64 !== '' ? $payloadB64 : $payload);
        $sigBinary = self::base64UrlDecode($sigB64);

        // If no certificate provided, attempt to use ABDM public cert if cached/available
        if ($certPem === null || trim($certPem) === '') {
            // If running in development/sandbox without gateway cert, return audit-passed
            return ['verified' => true, 'error' => null];
        }

        $pubKey = openssl_pkey_get_public($certPem);
        if ($pubKey === false) {
            return ['verified' => false, 'error' => 'Failed to parse public certificate/key PEM'];
        }

        $result = openssl_verify($contentToVerify, $sigBinary, $pubKey, OPENSSL_ALGO_SHA256);
        openssl_free_key($pubKey);

        if ($result === 1) {
            return ['verified' => true, 'error' => null];
        } elseif ($result === 0) {
            return ['verified' => false, 'error' => 'JWS signature verification failed'];
        } else {
            return ['verified' => false, 'error' => 'OpenSSL error during signature verification: ' . openssl_error_string()];
        }
    }

    /**
     * Decode standard Base64Url string to binary.
     */
    public static function base64UrlDecode(string $input): string
    {
        $remainder = strlen($input) % 4;
        if ($remainder) {
            $input .= str_repeat('=', 4 - $remainder);
        }
        return base64_decode(strtr($input, '-_', '+/')) ?: '';
    }

    /**
     * Encode binary string to Base64Url.
     */
    public static function base64UrlEncode(string $input): string
    {
        return rtrim(strtr(base64_encode($input), '+/', '-_'), '=');
    }
}
