<script src="<?= BASE_URL ?>assets/js/jquery-3.7.1.min.js"></script>
<script src="<?= BASE_URL ?>assets/js/jquery.nice-select.min.js"></script>
<script src="<?= BASE_URL ?>assets/js/bootstrap.bundle.min.js"></script>
<script src="<?= BASE_URL ?>assets/js/odometer.min.js"></script>
<script src="<?= BASE_URL ?>assets/js/jquery.appear.min.js"></script>
<script src="<?= BASE_URL ?>assets/js/swiper-bundle.min.js"></script>
<script src="<?= BASE_URL ?>assets/js/jquery.meanmenu.min.js"></script>
<script src="<?= BASE_URL ?>assets/js/jquery.magnific-popup.min.js"></script>
<script src="<?= BASE_URL ?>assets/js/wow.min.js"></script>
<script src="<?= BASE_URL ?>assets/js/gsap.min.js"></script>
<script src="<?= BASE_URL ?>assets/js/ScrollTrigger.min.js"></script>
<script src="<?= BASE_URL ?>assets/js/SplitText.min.js"></script>
<script src="<?= BASE_URL ?>assets/js/splitType.js"></script>
<script src="<?= BASE_URL ?>assets/js/main.js"></script>
<script src="<?= BASE_URL ?>assets/js/custom.js"></script>
